[theme]
base = "dark"
# Primary accent color.
primaryColor = "#B85042"

# Background color of the app.
backgroundColor = "#A7BEAE"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#E7E8D1"

# Color used for almost all text.
textColor = "#FFFFFF"